// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjuouwqsjanwnfhaecoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqdW91d3FzamFud25maGFlY29vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNTY5MDYsImV4cCI6MjA2NjYzMjkwNn0.FecPQwd9LkfD270wP0ePBWyH20CmM3IcCkOG4KLdJpw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});